on:
  workflow_dispatch:

permissions:
  id-token: write

env:
  BASE_BUILD_NAME: "legacy-gradle-plugin-build"
  JFROG_CLI_BUILD_NAME: "legacy-gradle-plugin-build-cli"
  GRADLE_BUILD_NAME: "legacy-gradle-plugin-build-gradle"
  JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
  AGGREGATED_BUILD_NAME: "legacy-gradle-plugin-build-aggregated"
  BUILD_NUMBER: ${{ github.run_number }}
  BUNDLE_NAME: "gradle-builds-test-bundle"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install jfrog cli
          uses: jfrog/setup-jfrog-cli@v4
          id: cli
          env:
            JF_URL: ${{ vars.JF_URL }}
          with:
            oidc-provider-name: github-oidc-integration
            oidc-audience: jfrog-github
            disable-auto-build-publish: true

        - name: Build and Publish with Gradle
          env:
            ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
            ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          run: |
            ./gradlew \
            build \
            artifactoryPublish \
            --info \
            --stacktrace
            
        - name: Decorate And Publish Second Build Info
          id: decorate-build-info
          run: |
            jf rt build-collect-env ${{ env.JFROG_CLI_BUILD_NAME }} ${{ github.run_number }} 
            jf rt build-add-git ${{ env.JFROG_CLI_BUILD_NAME }} ${{ github.run_number }}
            jf rt build-publish ${{ env.JFROG_CLI_BUILD_NAME }} ${{ github.run_number }}

        - name: Aggregate Build Infos With Same Name For Children
          run: |
            jf rt build-append ${{ env.AGGREGATED_BUILD_NAME }} ${{ github.run_number }} ${{ env.GRADLE_BUILD_NAME }} ${{ github.run_number }}
            jf rt build-append ${{ env.AGGREGATED_BUILD_NAME }} ${{ github.run_number }} ${{ env.JFROG_CLI_BUILD_NAME }} ${{ github.run_number }}
            jf rt build-publish ${{ env.AGGREGATED_BUILD_NAME }} ${{ github.run_number }}

        - name: Create release bundle
          id: create-release-bundle
          run: |
            echo '{ "files": [ {"build": "'"${{ env.AGGREGATED_BUILD_NAME }}/${{ github.run_number }}"'"} ] }' > bundle-spec.json
            jf release-bundle-create ${{ env.BUNDLE_NAME }} ${{ github.run_number }} \
            --signing-key "${{ secrets.GPG_KEY_NAME }}" \
            --spec bundle-spec.json \
            --sync=true
            NAME_LINK=${{ vars.JF_URL }}'/ui/artifactory/lifecycle/?bundleName='${{ env.BUNDLE_NAME }}'&bundleToFlash='${{ env.BUNDLE_NAME }}'&repositoryKey=example-project-release-bundles-v2&activeKanbanTab=promotion'
            VER_LINK=${{ vars.JF_URL }}'/ui/artifactory/lifecycle/?bundleName='${{ env.BUNDLE_NAME }}'&bundleToFlash='${{ env.BUNDLE_NAME }}'&releaseBundleVersion='${{ github.run_number }}'&repositoryKey=example-project-release-bundles-v2&activeVersionTab=Version%20Timeline&activeKanbanTab=promotion'
            echo '📦 Release bundle ['${{ env.BUNDLE_NAME }}']('${NAME_LINK}'):['${{ github.run_number }}']('${VER_LINK}') created' >> $GITHUB_STEP_SUMMARY