on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install jfrog cli
          uses: jfrog/setup-jfrog-cli@v4
          id: cli
          env:
            JF_URL: https://tomjfrog.jfrog.io
          with:
            oidc-provider-name: github-oidc-integration
            oidc-audience: jfrog-github
            disable-auto-build-publish: true

        - name: Build and Publish with Gradle
          env:
            ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
            ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
            BUILD_NUMBER: ${{ github.run_number }}
          run: |
            ./gradlew build artifactoryPublish--info --stacktrace
            
